# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import ethereum_pb2 as ethereum__pb2


class ProtoEthServiceStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTransaction = channel.unary_unary(
                '/protoeth.ProtoEthService/GetTransaction',
                request_serializer=ethereum__pb2.GetTxReq.SerializeToString,
                response_deserializer=ethereum__pb2.TransactionInfo.FromString,
                )


class ProtoEthServiceServicer(object):
    """Missing associated documentation comment in .proto file"""

    def GetTransaction(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProtoEthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTransaction,
                    request_deserializer=ethereum__pb2.GetTxReq.FromString,
                    response_serializer=ethereum__pb2.TransactionInfo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'protoeth.ProtoEthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ProtoEthService(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def GetTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protoeth.ProtoEthService/GetTransaction',
            ethereum__pb2.GetTxReq.SerializeToString,
            ethereum__pb2.TransactionInfo.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
